pipeline {
    agent any

    stages {
        stage('Run Python Script') {
            steps {
                script {
                    def pythonScript = """
                    print("Hello Python")
                    """
                    writeFile file: 'hello.py', text: pythonScript
                    sh 'python hello.py'
                }
            }
        }
    }
}
